### ISSUE TITLE
sweep: figure out a better solution to do https://github.com/beetcb/ghdl/commit/1f17aa96e33c912de7557612df3e628d5f91ebaf

### ISSUE THREAD

**Issue by yaonyan** [beetcb/ghdl#3]
https://github.com/beetcb/ghdl/blob/f53255a2ab0f2fae3f8018262f1a072b2e9cd521/dl.go#L72

**Comment by yaonyan** [comment]
And .dmg, and other possible os-specific binary file extensions as well

**Comment by yaonyan** [comment]
sweep: read this issue

**Comment by kevinlu1248** [comment]
Hey sorry about this. I'm one of the developers of Sweep. We're taking a look at this issue.

**Comment by yaonyan** [comment]
Thank you for the active support, the description and comments of the issue might be a bit vague though, tbh

But I see the generated plan seems doable.

**Comment by yaonyan** [comment]
The plan actually is my solution that has been committed yesterday, maybe that causes conflicts and  preventing a PR from been created

**Comment by wwzeng1** [comment]
Yep that would cause an issue

**Comment by yaonyan** [comment]
sweep: figure out a better solution to do https://github.com/beetcb/ghdl/commit/1f17aa96e33c912de7557612df3e628d5f91ebaf

**Comment by yaonyan** [comment]
> Yep that would cause an issue

Tricky one here 🤣

**Comment by kevinlu1248** [comment]
Ya it's a problem at the execution stage. We have a solution in the works that I'm just testing right now.

**Comment by kevinlu1248** [comment]
Hey @beetcb we just deployed the fix. It should do a lot better now at execution.

**Comment by yaonyan** [comment]
thanks !
